floor_bump = loadtexture("Textures\\Floor_Bump.jpg")

camera = createcamera()
setposition(camera, 0, 8, -20)
setangle(camera, 15, 0)
setclscolor(camera, 20, 20, 20)
setfogenabled(camera, true)
setfogrange(camera, 100)

light = createlight()
setposition(light, -5, 13, -2)
setsize(light, 1, 1, 1)
setcolor(light, 50, 60, 230)
setbrightness(light, 8)
light = createlight()
setposition(light, 5, 13, 0)
setsize(light, 1, 1, 1)
setcolor(light, 250, 200, 0)
setbrightness(light, 8)

plane = createplane()
setcolor(plane, 127, 127, 127)
setreflection(plane, .5)
setspecular(plane, 200, 5)
setbumpmap(plane, floor_bump, 5, 5, .1)

sphere = createsphere()
setposition(sphere, -8, 3, 0)
setradius(sphere, 3)
setcolor(sphere, 0, 0, 0)
setreflection(sphere, 1)
setspecular(sphere, 15, .05)
sphere = createsphere()
setposition(sphere, 0, 3, 0)
setradius(sphere, 3)
setcolor(sphere, 127, 127, 127)
setreflection(sphere, .5)
setspecular(sphere, 15, .05)
sphere = createsphere()
setposition(sphere, 8, 3, 0)
setradius(sphere, 3)
setcolor(sphere, 240, 240, 240)
setreflection(sphere, .1)
setspecular(sphere, 15, .05)
cube = createcube()
setposition(cube, -8, 1, -5)
setsize(cube, 2, 2, 2)
setcolor(cube, 0, 255, 127)
cylinder = createcylinder()
setposition(cylinder, 0, 1, -5)
setheight(cylinder, 2)
setcolor(cylinder, 255, 0, 0)
tube = createtube()
setposition(tube, 8, 1, -5)
setheight(tube, 2)
setcolor(tube, 0, 127, 255)

render(camera)