bricks = loadtexture("Textures\\Bricks.jpg")
bricks_bump = loadtexture("Textures\\Bricks_Bump.jpg")
crate = loadtexture("Textures\\Crate.jpg")
crate_bump = loadtexture("Textures\\Crate_Bump.jpg")
earth = loadtexture("Textures\\Earth.jpg")
earth_bump = loadtexture("Textures\\Earth_Bump.jpg")
face = loadtexture("Textures\\Face.jpg")
face_bump = loadtexture("Textures\\Face_Bump.jpg")
stones = loadtexture("Textures\\Stones.jpg")
stones_bump = loadtexture("Textures\\Stones_Bump.jpg")
tiles = loadtexture("Textures\\Tiles.jpg")
tiles_bump = loadtexture("Textures\\Tiles_Bump.jpg")

camera = createcamera()
setposition(camera, 0, 12, -20)
setangle(camera, 20, 0)
setambientlight(camera, 20, 50, 60)

light = createlight()
setposition(light, -14, 8, -5)
setsize(light, 1, 1, 1)
setcolor(light, 50, 80, 160)
setbrightness(light, 10)
light = createlight()
setposition(light, 0, 8, -5)
setsize(light, 1, 1, 1)
setcolor(light, 20, 255, 40)
setbrightness(light, 10)
light = createlight()
setposition(light, 14, 8, -5)
setsize(light, 1, 1, 1)
setcolor(light, 255, 180, 80)
setbrightness(light, 10)

plane = createplane()
setreflection(plane, .5)
setspecular(plane, 100, 1)
settexture(plane, tiles, 10, 10)
setbumpmap(plane, tiles_bump, 10, 10, .2)

cube = createcube()
setsize(cube, 100, 50, 0)
setposition(cube, 0, 25, 5)
setcolor(cube, 80, 80, 80)
setreflection(cube, 1)
setspecular(cube, 30, .1)
settexture(cube, face, .1, .2)
setbumpmap(cube, face_bump, .1, .2, .2)
cube = createcube()
setsize(cube, 0, 50, 100)
setposition(cube, -18, 25, -5)
setcolor(cube, 80, 80, 80)
setreflection(cube, 1)
setspecular(cube, 30, .1)
settexture(cube, face, .1, .2)
setbumpmap(cube, face_bump, .1, .2, .2)
cube = createcube()
setsize(cube, 0, 50, 100)
setposition(cube, 18, 25, -5)
setcolor(cube, 80, 80, 80)
setreflection(cube, 1)
setspecular(cube, 30, .1)
settexture(cube, face, .1, .2)
setbumpmap(cube, face_bump, .1, .2, .2)

cube = createcube()
setposition(cube, -12, 2.5, 0)
setsize(cube, 5, 5, 5)
setcolor(cube, 220, 220, 220)
settexture(cube, crate)
setbumpmap(cube, crate_bump, 1, 1, 1.5)
sphere = createsphere()
setposition(sphere, -3, 3, 0)
setradius(sphere, 3)
setspecular(sphere, 15, .1)
settexture(sphere, earth)
setbumpmap(sphere, earth_bump)
cylinder = createcylinder()
setposition(cylinder, 4.5, 2.5, 0)
setradius(cylinder, 2)
setheight(cylinder, 5)
setspecular(cylinder, 10, .2)
settexture(cylinder, bricks, .5, 2)
settexture2(cylinder, bricks, 2, 2)
setbumpmap(cylinder, bricks_bump, .5, 2, 1)
setbumpmap2(cylinder, bricks_bump, 2, 2, 1)
tube = createtube()
setposition(tube, 12, 2.5, 0)
setradius(tube, 2)
setinnerradius(tube, 1)
setheight(tube, 5)
setcolor(tube, 150, 150, 150)
setreflection(tube, .1)
setspecular(tube, 10, .3)
settexture(tube, stones, .5, 2)
settexture2(tube, stones, 2, 2)
setbumpmap(tube, stones_bump, .5, 2, .75)
setbumpmap2(tube, stones_bump, 2, 2, .75)

render(camera)